# Generated by Django 3.1.5 on 2021-01-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210117_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organisations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
