# Generated by Django 3.1.5 on 2021-01-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
