# Generated by Django 3.1.5 on 2021-01-23 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20210122_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='date_added',
        ),
    ]
