# Generated by Django 3.1.5 on 2021-01-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_remove_lead_converted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='profile_picture',
        ),
    ]
